name: 'level_analyst_analytics'
version: '1.0.0'
config-version: 2

profile: 'level_analyst'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  level_analyst_analytics:
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table
      mart_demand_weighted:
        +materialized: view

tests:
  +store_failures: true

vars:
  # Timezone for daypart calculations
  local_timezone: 'America/Chicago'

  # Daypart definitions
  morning_start_hour: 0
  morning_end_hour: 16
  evening_start_hour: 16
  evening_end_hour: 24