version: '3.8'

services:
  analyst-api:
    build:
      context: ./services/analyst
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8088}:8088"
    environment:
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - SUPABASE_DB_URL_RO=${SUPABASE_DB_URL_RO}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_PUBLIC_KEY_BASE64=${JWT_PUBLIC_KEY_BASE64}
      - DEV_JWT_HS256_SECRET=${DEV_JWT_HS256_SECRET}
      - DEV_ZONE_IDS=${DEV_ZONE_IDS}
      - ORG_ID=${ORG_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_FAST=${OPENAI_MODEL_FAST}
      - OPENAI_MODEL_REASON=${OPENAI_MODEL_REASON}
      - RATES_API_BASE_URL=${RATES_API_BASE_URL}
      - RATES_API_TOKEN=${RATES_API_TOKEN}
      - API_PORT=${API_PORT:-8088}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
      - ANALYST_AUTO_APPLY=${ANALYST_AUTO_APPLY}
      - ANALYST_REQUIRE_APPROVAL=${ANALYST_REQUIRE_APPROVAL}
      - TZ=${TZ}
      - GUNICORN_BIND=${GUNICORN_BIND:-0.0.0.0:8088}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-60}
      - GUNICORN_GRACEFUL_TIMEOUT=${GUNICORN_GRACEFUL_TIMEOUT:-90}
    volumes:
      - ./services/analyst/static:/app/static:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: level-analyst-network
